# -*- coding: utf-8 -*-
"""basic_dataAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSfON0xENWlSF7nO4wgIJE1ZTbrDxw3f
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qU langchain langchain-openai langchain-community langchain-experimental pandas

import os
os.environ["OPENAI_API_KEY"] = "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"
os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGSMITH_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGSMITH_API_KEY"] = "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"
os.environ["LANGSMITH_PROJECT"] = "pr-flowery-burst-44"

import pandas as pd

df = pd.read_csv("myntra.csv")

print(df.shape)

df.columns

from langchain_core.prompts import ChatPromptTemplate
from langchain_experimental.tools import PythonAstREPLTool

tool = PythonAstREPLTool(locals={"df": df})

tool.invoke("df['Price (INR)'].mean()")

from langchain.agents import initialize_agent
from langchain.agents import Tool
from langchain.agents import AgentType

tools = [Tool(name=tool.name, func=tool.invoke, description=tool.description)]

# Initialize the agent
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)





# from langchain.prompts import ChatPromptTemplate
# from langchain.chat_models import ChatOpenAI # Import ChatOpenAI from langchain.chat_models
# llm = ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo")
# llm_with_tools = llm.bind_tools([tool], tool_choice=tool.name)

prompt_template = ChatPromptTemplate.from_template(
   """ I have a pandas DataFrame named 'df' containing data about products from Myntra.

The DataFrame has the following columns:
- 'ProductID' : The unique identifier for each product.
- 'ProductName': The name of the product.
- 'ProductBrand': The brand name of the product.
- 'Gender': The gender the product is suitable for (e.g., Men, Women).
- 'Price (INR)': The price of the product in Indian Rupees.
- 'NumImages' : The number of images of the particular product.
- 'Description' : The description of the product.
- 'Primary Color': The primary color of the product.


I want you to be able to answer a wide variety of questions about this dataset, including:

- What are the most popular brands?
- What are the average prices of products by brand?
- What are the most common colors for different product types?
- Can you identify any trends or patterns in the data?

Please provide clear and concise answers, including relevant code snippets or visualizations to support your findings.

Make sure to consider the data types of the columns and handle any missing values appropriately."""
)

prompt = prompt_template.format()

response = agent.run(prompt)

print(response.content)
exec(response.content)

pip install langchain-huggingface

from langchain_huggingface import HuggingFaceEndpoint
from langchain.llms import HuggingFaceHub